SCALING = 1.5

MAP_SIZE = (18, 32)

# grid & screen for display only
GRID_WIDTH = 20  # 22.5
GRID_HEIGHT = 20
SCREEN_HEIGHT = (MAP_SIZE[1]) * GRID_HEIGHT  # +12
SCREEN_WIDTH = MAP_SIZE[0] * GRID_WIDTH

# SCENE OBJECTS

KING_TOWER_HEIGHT = 4
KING_TOWER_WIDTH = 4

KING_TOWER_X = MAP_SIZE[0] // 2
ENEMY_KING_TOWER_X = KING_TOWER_X
PLAYER_KING_TOWER_X = KING_TOWER_X

ENEMY_KING_TOWER_Y = 3
PLAYER_KING_TOWER_Y = MAP_SIZE[1] - ENEMY_KING_TOWER_Y


PRINCESS_TOWER_HEIGHT = 3
PRINCESS_TOWER_WIDTH = 3

PRINCESS_TOWER_LEFT_X = 3.5
PRINCESS_TOWER_RIGHT_X = MAP_SIZE[0] - PRINCESS_TOWER_LEFT_X

ENEMY_PRINCESS_TOWER_LEFT_X = PRINCESS_TOWER_LEFT_X
ENEMY_PRINCESS_TOWER_RIGHT_X = PRINCESS_TOWER_RIGHT_X
PLAYER_PRINCESS_TOWER_LEFT_X = PRINCESS_TOWER_LEFT_X
PLAYER_PRINCESS_TOWER_RIGHT_X = PRINCESS_TOWER_RIGHT_X

ENEMY_PRINCESS_TOWER_Y = 6.5
ENEMY_PRINCESS_TOWER_LEFT_Y = ENEMY_PRINCESS_TOWER_Y
ENEMY_PRINCESS_TOWER_RIGHT_Y = ENEMY_PRINCESS_TOWER_Y


PLAYER_PRINCESS_TOWER_Y = MAP_SIZE[1] - ENEMY_PRINCESS_TOWER_Y
PLAYER_PRINCESS_TOWER_LEFT_Y = PLAYER_PRINCESS_TOWER_Y
PLAYER_PRINCESS_TOWER_RIGHT_Y = PLAYER_PRINCESS_TOWER_Y


BRIDGE_WIDTH = 2
BRIDGE_HEIGHT = 2

BRIDGE_Y = MAP_SIZE[1] // 2
BRIDGE_LEFT_X = 3.5
BRIDGE_RIGHT_X = MAP_SIZE[0] - BRIDGE_LEFT_X


RAGE_PURPLE = (255, 0, 255)
SLOW_BLUE = (202, 225, 255)
RAGE_SLOW_MIXED = (229, 113, 255)

fps = 30
DELTA_TIME = 1 / fps


# colors
GREEN = (102, 204, 0)
BROWN = (139, 69, 19)
BLUE = (0, 102, 255)
RED = (255, 22, 0)
ORANGE = (255, 165, 0)
LIGHT_BLUE = (30, 150, 255)
LIGHT_RED = (255, 80, 30)
GRAY = (169, 169, 169)
BLACK = (0, 0, 0)
PINK = (189, 52, 205)
ROAD_COLOR = (182, 157, 102)
